# Generated by Django 3.1.3 on 2020-11-09 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botdevtestbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramstate',
            name='telegram_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_states', to='botdevtestbot.telegramchat'),
        ),
        migrations.AlterField(
            model_name='telegramstate',
            name='telegram_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_states', to='botdevtestbot.telegramuser'),
        ),
    ]
